version: '3.8'

services:
  qwen-vl_description:
    image: qwen-vl_description:latest
    restart: unless-stopped
    ports:
      - "8015:8015"
    env_file:
      - .env
    volumes:
      - './models_cache:/app/models_cache'
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://localhost:8015/health" ]
    #   interval: 1m30
    #   timeout: 5s
    #   start_period: 60s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "2" ]
              capabilities: [gpu]
